# Minimal Backtest Configuration
backtest:
  period:
    start: "2023-01-01"
    end: "2024-01-01"

  symbols: [AAPL, MSFT, SPY, TSLA]

  strategies: [momentum_H4, momentum_H1]
  
  account:
    initial_deposit: 10000.0
    leverage: 100
  
  risk:
    risk_per_trade_pct: 2.0
